apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: vote-app-dev-run
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master, main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  pipelineSpec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repository
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: git-clone
            - name: namespace
              value: openshift-pipelines
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: URL
            value: "{{ repo_url }}"
          - name: REVISION
            value: "{{ revision }}"

      - name: run-tests
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: run-unit-tests
            - name: namespace
              value: pipelines-tutorial
        params:
          - name: CONTEXT_DIR
            value: "."
        workspaces:
          - name: source
            workspace: shared-workspace
        runAfter:
          - fetch-repository

      - name: build-image
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: buildah-local
            - name: namespace
              value: pipelines-tutorial
        params:
          - name: IMAGE
            value: "image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/{{ repo_name }}:{{ revision }}"
          - name: CONTEXT_DIR
            value: "."
          - name: DOCKERFILE
            value: "Dockerfile"
        workspaces:
          - name: source
            workspace: shared-workspace
        runAfter:
          - run-tests

      - name: update-gitops-manifest
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: git-update-manifest
            - name: namespace
              value: pipelines-tutorial
        params:
          - name: git-config-repo
            value: "https://github.com/adregis/vote-app-config.git"
          - name: environment
            value: "dev"
          - name: app-name
            value: "{{ repo_name }}"
          - name: image-tag
            value: "image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/{{ repo_name }}:{{ revision }}"
        workspaces:
          - name: source
            workspace: shared-workspace
        runAfter:
          - build-image

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi